### ISSUE TITLE
API Key or Access Token?

### ISSUE THREAD

**Issue by OKNoah** [tanepiper/node-bitly#10]
The docs here say to use an `API key`. But the bitly dev site just has `client ID`, `client secret` and `access token`. Which is the API key?

**Comment by tanepiper** [comment]
@OKNoah Hi, by the looks of it this is using the OAuth API, which the library doesn't support yet.  You need to currently use the deprecated API key at https://bitly.com/a/your_api_key

I'll be looking to add OAuth support in version 3.0

**Comment by tanepiper** [comment]
@OKNoah This has been resolved in the latest release and now uses an access token that can be generated at the bitly website.
