### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by tharrington** [tanepiper/node-bitly#17]
I have installed via npm and copied the code including my oauth token... I get an undefined error:

```
TypeError: undefined is not a function
at new Bitly (../node_modules/bitly/lib/bitly.js:33:26) 
```

with the following code:

```

var Bitly 		= require('bitly');
var bitly 		= new Bitly('my token');

```

This is pretty elementary, am I missing something obvious?

**Comment by tanepiper** [comment]
@tharrington It would suggest that it's throwing an error within the library itself.

The specific line is:

`this.config = Object.assign({ access_token: accessToken }, config, {`

What version of node are you running?  This is a standard part of ES6 now, and has been in node since version 4.

**Comment by tharrington** [comment]
when i run $ node -v 

it shows v0.12.4

What is going on with node versioning? The 0.12.4 vs version 4, why the disparity?

**Comment by g11baldwin** [comment]
@tharrington I encountered the same issue running Node 0.12.7 on Mac OSX 10.11.2. After upgrading to Node 4.3 LTS the issue went away, and functionality of @tanepiper bitly solution is working fine.

**Comment by g11baldwin** [comment]
@tanepiper - Nice bitly package! Thank you for sharing it.

**Comment by tanepiper** [comment]
@tharrington https://medium.com/node-js-javascript/4-0-is-the-new-1-0-386597a3436d#.fv7mz1edn https://www.quora.com/Why-did-node-stable-version-number-jumps-from-directly-0-12-x-to-4-x
