### ISSUE TITLE
This uri always gives 500

### ISSUE THREAD

**Issue by nikhileshva** [tanepiper/node-bitly#18]
I am sending this uri - 

```
http://xyz.com/ByS-58?referenceNo=34C49D14&productId=1&restaurantId=1186&orderType=1
```

This is my code

```
return bitlyApi.shorten(requestUrl)
                .then((response) => {
                    logger.info(`[BitlyService] got successful response from bitly for ${JSON.stringify(request)} response: ${JSON.stringify(response)}`);
                    request.bitlyUrl = response.data.url;
                    return resolve(request);
                })
                .catch((error) => {
                    logger.info("[BitlyService] got error from bitly");
                    return reject(error);
                });
```

This is the response that I get:

```
{\"data\":[],\"status_code\":500,\"status_txt\":\"INVALID_URI\"}
```

However when I request this url from my bitly account, it works properly

**Comment by bendapkiewicz** [comment]
Why is this closed the same day it was opened? Was it resolved? Experiencing the same issue and would like to know if there was an actual resolution.

**Comment by tanepiper** [comment]
@bendapkiewicz Not sure it was the OP who closed it.

As the request is being made to Bit.ly and they are returning a 500, you may have to check that you are in fact sending a valid URI.

Can you share more information about what you are actually trying to do?

**Comment by BearMaverick** [comment]
I don't remember the exact resolution, but it had to something with url. 
Maybe there was an issue with building url in post payload.
