### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by nparsons08** [tanepiper/node-bitly#20]
This POS doesn't work. Hitting the REST API over this. Keep an eye out for a new bit.ly module from nparsons08.

**Comment by specious** [comment]
I'm using [v3.0.3](https://github.com/tanepiper/node-bitly/tree/1397b3842c87838739728818f9fdf4dabb2e3a78) with [specious/bitly-client](https://github.com/specious/bitly-client) which is quite solid.

**Comment by tanepiper** [comment]
@nparsons08 @specious Thanks for reporting it, I'll try get around to looking at it - in the meantime if there is a pull request I can look at that too
