### ISSUE TITLE
Bitly.shorten(...).then is not a function | Node 9.0.0

### ISSUE THREAD

**Issue by shiyasjxt** [tanepiper/node-bitly#40]
Trying to run below code and throwing the error - Bitly.shorten(...).then is not a function

const url='myurl';

Bitly.shorten(url)
.then(
  results =>{
    // Do something with your new, shorter url...
    const obj = JSON.parse(results);
    //having a global variable is not a good idea
    // shorturl= obj.data.url;
    console.log("got data:",obj.data.url);
    return obj.data.url;
  }
)
.then(
  shorturl => {
    //do something with short url
  }
)
.then(
  undefined
  ,reject =>//handle any errors
    console.error("Failed:",reject)
);

**Comment by tanepiper** [comment]
@shiyasjxt You code example is unreadable, can you please use styling with markdown.  Also if you are new to node I would not recommend using Node 9
