### ISSUE TITLE
shorten does not create a custom domain if it is the default

### ISSUE THREAD

**Issue by lukepighetti** [tanepiper/node-bitly#43]
according to the Bitly API docs, if you do a `shorten` request, it will use a custom domain if it is the default. http://dev.bitly.com/links.html#v3_shorten

However, with node-bitly, no matter what your default is, it always creates a bit.ly domain link.

Am I missing something? :)

**Comment by tanepiper** [comment]
@lukepighetti can you provide an example of you using it?

**Comment by lukepighetti** [comment]
if you use shorten, you get bit.ly domain, not your default custom domain

**Comment by tanepiper** [comment]
@lukepighetti I think I've identified the issue, yes it's possibly not being passed.  I don't have a custom domain so I'm not sure it's been tested.  I'll have a look at it this evening.

**Comment by tanepiper** [comment]
@lukepighetti In your package.json can you set bitly to `beta` as your version, this should download `5.0.12-beta.786`. Can you try that, passing `domain` with your custom domain.

e.g.

```js
const bitly = BitlyClient(API_KEY, { domain: 'my.ly' });
```
