### ISSUE TITLE
When i use your module in my typescrip app 

### ISSUE THREAD

**Issue by forgr-owner** [tanepiper/node-bitly#61]
node_modules/bitly/src/lib.ts:1:8 - error TS1192: Module '"url"' has no default export.

1 import url, { UrlWithStringQuery } from 'url';

**Comment by g-ongenae** [comment]
I have the same problem.

The `url` module is not in the package's dependencies.
https://github.com/tanepiper/node-bitly/blob/5d92ea172d65180013fc07a7b52de86faaf200a0/package.json#L73-L77

Also, tsc says `generateUrl` is not used here:
https://github.com/tanepiper/node-bitly/blob/5d92ea172d65180013fc07a7b52de86faaf200a0/src/bitly.ts#L1

**Comment by tanepiper** [comment]
@forgr-owner Merged in and will be available in the next release shortly.
