### ISSUE TITLE
Could not find a declaration file for module bitly

### ISSUE THREAD

**Issue by aliiqbalIntelligenes** [tanepiper/node-bitly#68]
![Capture 1](https://user-images.githubusercontent.com/51798492/59457782-89a03e00-8e32-11e9-9885-61460ee8bfa2.PNG)
![Capture 2](https://user-images.githubusercontent.com/51798492/59457783-8a38d480-8e32-11e9-8c5a-2b41c5a65ea1.PNG)
![Capture 3](https://user-images.githubusercontent.com/51798492/59457784-8a38d480-8e32-11e9-8b61-594510f4f646.PNG)
![Capture](https://user-images.githubusercontent.com/51798492/59457785-8ad16b00-8e32-11e9-83bc-5ab90014dda1.PNG)

**Comment by aliiqbalIntelligenes** [comment]
I'm using Angular and Typescript.

**Comment by aliiqbalIntelligenes** [comment]
Can you please share the expected time to resolve this issue? I'm using this package in my project which causes delay because of this issue. Thanks.

**Comment by tanepiper** [comment]
Hi @aliiqbalIntelligenes - as this is open source I don't really maintain I cannot give a timescale yet.  I have a potential quick fix, but at the moment I need to resolve an issue with the CI pipeline as some tokens have expired.

I'll let you know when the beta of the potential fix is out, if it doesn't work then it means re-writing part of the library and pipeline for publishing, and also I have other work and commitments right now.

**Comment by aliiqbalIntelligenes** [comment]
Ok Thanks.

**Comment by tanepiper** [comment]
@aliiqbalIntelligenes Issue has been fixed, upgrade to 6.1.0

**Comment by aliiqbalIntelligenes** [comment]
@tanepiper Thank you so much.

**Comment by aliiqbalIntelligenes** [comment]
It was not working, i create a new issue: https://github.com/tanepiper/node-bitly/issues/70
