### ISSUE TITLE
Shortener should call back with error when get 500 error from Bitly

### ISSUE THREAD

**Issue by oveddan** [tanepiper/node-bitly#7]
If you call Bitly.shorten, and the api gives you an error, the method calls back with the data:
{ data: [], status_code: 500, status_txt: 'INVALID_URI' }

This happens if for example you pass it a url without a slash at the end.

It should be calling back with an error.

**Comment by haydenbleasel** [comment]
Same with INVALID_APIKEY, should return as an error.

**Comment by tanepiper** [comment]
@haydenbleasel Can you provide a test case for this showing the issue?  My apologies but I haven't updated this module in a while.  Happy to look at fixing it

**Comment by haydenbleasel** [comment]
```js
var Bitly = require('bitly');
var bitly = new Bitly('haydenbleasel', 'XXXXXXXXXXXXXXXX');
bitly.shorten('https://github.com/tanepiper/node-bitly', function(err, response) {
  console.log(err); // null
  console.log(response); // { data: [], status_code: 500, status_txt: 'INVALID_APIKEY' }
});
```

Same goes for @oveddan's issue I think.

**Comment by tanepiper** [comment]
@haydenbleasel @oveddan Hi folks, this should be resolved now.

The callback (and new promise api) returns an error on this now.

**Comment by oveddan** [comment]
Thanks @haydenbleasel

**Comment by tanepiper** [comment]
@oveddan Apologies for it taking so long - hopefully this new version will fit your needs.

**Comment by meddey-tech** [comment]
I have same issue when using this api on web application..

**Comment by tanepiper** [comment]
@meddey-tech The version discussed before was for Bitly API v3 - the API is now v4, are you using the correct version of the library?
