### ISSUE TITLE
Request returned 403: RATE_LIMIT_EXCEEDED"}

### ISSUE THREAD

**Issue by RichyNs** [tanepiper/node-bitly#71]
I'm trying to generate over +100k shorten URL after 121 url it throws this error : 
{"status":500,"message":"[node-bitly] Request returned 403: RATE_LIMIT_EXCEEDED"}.

Is there a way I can generate as much as possible ?

**Comment by tanepiper** [comment]
The error message literally tells you the problem - you have hit API limits with Bitly, this is nothing to do with the library

**Comment by RichyNs** [comment]
My question was : is there a way to generate thousands of shorten URL ??

**Comment by tanepiper** [comment]
Hi @RichyNs I don't work for Bitly, and this library is no longer actively maintained - this is not something I will provide support on.

**Comment by RichyNs** [comment]
Okay thanks.
