### ISSUE TITLE
Bitly will deactivate v3 API on March 1, 2020; need to migrate to v4

### ISSUE THREAD

**Issue by specious** [tanepiper/node-bitly#72]
@tanepiper, thank you so much for creating and maintaining this project.

As the maintainer of [bitly-client](https://github.com/specious/bitly-client) which entirely relies on this library for access to the Bitly API, I felt personally touched by the announcement that the v3 API will be officially deactivated on March 1, 2020:

![bitly-v3-api-deactivation-announcement](https://user-images.githubusercontent.com/451178/66446252-ca424980-ea17-11e9-97c1-cb8ba5e41741.png)

As this library currently [relies on v3](https://github.com/tanepiper/node-bitly/blob/b64e7c54c798404476422e06821de975504bc587/src/lib.ts#L20), I decided to open an issue on this topic.

The [official migration guide](https://dev.bitly.com/v4/#section/Migrating-from-V3) is available.

**Comment by remi2j** [comment]
From the readme:
>Version 6.1.x will introduce Bitly v4 support
The latest node-bitly version is 6.1.0. Does this mean there is a plan to update it?

**Comment by tanepiper** [comment]
@remi2j no plans, I have no intention of continuing to support this library but if someone would like to add support I'm happy to work with them to release it (as I already have pipelines set up to release it to mom)

**Comment by babkouew** [comment]
[ [Firestore-shorten-urls-bitly] Extension will break down if not updated to Bitly APIv4 by deadline March 1st, 2020]()

**Comment by joshuatz** [comment]
@tanepiper Hi! I'd like to lend a hand if you are still looking at assistance on this. I've noticed you have started a PR [here](https://github.com/tanepiper/node-bitly/pull/73), but marked as "help wanted".

I've taken a cursory glance through, and I think I can see where and how the tests and endpoints will need to get updated (for example, Bitly no longer returns a global hash on shortening, and many of the endpoints have migrated from POSTs to GETs, such as `referrers_by_domain` -> `referring_domains`).

If you'd like, I can work on addressing those issues, and then make a PR into the `bitly-v4-support` branch. I could probably have something ready in a day or two.

**Comment by joshuatz** [comment]
@tanepiper I don't want to bug you, but I went ahead and took a pass at the upgrade. Everything is functional with the V4 API, and the tests are passing - you can check it out [here](https://github.com/joshuatz/node-bitly/tree/joshua/bitly-v4-support). I still need to update the Readme, docs, and version-bump, but before I do any of that, I wanted to see if:

 - A) You are going to be open to a PR, and
 - B) If so, can you answer some questions on specific changes? I can either post those questions here on this issue, or if you prefer, open the PR and post them there.

**Comment by vany0114** [comment]
@joshuatz thanks for taking care of this!

@tanepiper, @joshuatz any plans to merge the PR and release the new version supporting the v4? The end of v3 is gonna be this week.
