### ISSUE TITLE
shorten should call /v4/shorten rather than /v4/bitlinks

### ISSUE THREAD

**Issue by tlugger** [tanepiper/node-bitly#77]
We provide two endpoints to shorten links with the Bitly API. 

[/v4/bitlinks](https://dev.bitly.com/v4/#operation/createFullBitlink) allows for more inputs in the POST body but is typically less performant and has a lower rate limit. 
[/v4/shorten](https://dev.bitly.com/v4/#operation/createBitlink) allows for fewer data in the POST body (only long_url *required, group_guid, and domain) and has a higher rate limit.

The shorten function in this package should call 'shorten' rather than 'bitlinks' to help with users facing rate limit issues: https://github.com/tanepiper/node-bitly/blob/437a27d9f644043973192eb2785482e79aecb625/src/bitly.ts#L74

**Comment by tanepiper** [comment]
@tlugger Thanks, releases as `7.1.0`
